defaults = {
            crossDomain: true, 
            // send request while on request is already being processing.
            multipleRequests: true, 
            checkValidationBeforeSendingRequest: true,
            dontSendSameRequestTwice: true,
            disableInputOnValidation: true,
            focusPersistIfNotValid: true,
            hideOnValidation: false,
            placeHolder: "",
            placeHolderValue: "",
            placeHolderDisable: false,
            dontPaginateIfDataLessThan: 4000,
            isDynamicLoad: true,
            isTag: false,
            isLiveSearch: false,
            isOdata: false,
            isMultipleSelect: true,
            isSelectFirstIndexByDefault: true,
            submitMethod: "Get",
            isRequired: true,
            oDataRelationsList: [],
            isPaginationEnable: false,
            pageSize: 30,
            totalItemsCountOnServer: 0,
            currentPage: 1,
            maxDisplayItems: 10,
            displayField: "display",
            searchingField: "display",
            valueField: "id",
            valueSelected: "",
            selectsFistOneByDefault: true,
            url: "",
            searchingUrl: "?search=@searchingKeyword",
            searchingVariable: "@searchingKeyword",
            delay: 250,
            nextPageUrl: "?Page=@pageNumber",
            pagingVariableName: "@pageNumber",
            selfUI: false,
            isOptimized: true,
            additionalCSS: "",
            singleItemClass: "",
            isDependableCombo: true,
            isSearchOnServerSide: true,
            dependablePropertyName: "",
            inputValidationRegularExpression: "",
            elementCreatingId: "",
            elementName: "",
            isCustomHtml: true,
            searchType: {
                startsWith: true,
                contains: false,
                equal: false,
                notEqual: false,
                custom: ""
            },
            messages: {
                spinnerIcon: "Requesting data...",
                validIcon: "Given input is valid.",
                invalidIcon: "Given input is invalid.",
                searchIcon: "Search data...",
                errorIcon: "Sorry! Can't retrieve data."
            },
            selectors: {
                label: ".jq-server-combo-label",
                comboImplement: ".jq-server-combo-implement",
                divContainer: ".form-combo",
                additionalFields: [
                    "[name=__RequestVerificationToken]"
                ]
            },
            attributes: {
                url: "data-url",
                isValidate: "data-is-validate",
                submitMethod: "data-submit-method",
                propertyFieldName: "data-name"
            },
            icons: {
                invalid: "jq-combo-icon-invalid fa fa-times",
                valid: "jq-combo-icon-valid fa fa-check",
                spinner: "jq-combo-icon-spinner fa fa-refresh fa-spin-custom",
                error: "jq-combo-icon-error fa fa-exclamation-circle",
                search: "jq-combo-icon-search fa fa-search",
                caret: "jq-combo-icon-caret fa fa-caret-down",
                iconList: "jq-combo-icons-list",
                iconWrapper: "jq-combo-icons-wrapper"
            },
            cssClass: {
                input: "jq-combo-input form-control",
                inputHover: "jq-combo-hover",
                comboHidden: "jq-combo-hidden",
                combo: "jq-combo",
                comboClick: "jq-combo-click",
                comboOpen: "jq-combo-open",
                comboHover: "jq-combo-hover-over",
                styleSetName: "default-style",
                listItem: "", // jq-combo-list-item
                list: "jq-combo-list",
                listDisplayWrapper: "jq-combo-list-wrapper",
                requestSending: "jq-combo-requesting-to-server",
                wrapper1: "first-wrapper-container",
                wrapper2: "second-wrapper-container",
                wrapper3: "third-wrapper-container",
                wrapper4: "forth-wrapper-container",
                hiddenClass: "jq-combo-hidden-element"
            },

            iconsIdPrefixes: {
                invalidIcon: "jq-combo-icon-invalid-",
                validIcon: "jq-combo-icon-valid-",
                spinnerIcon: "jq-combo-icon-spinner-",
                errorIcon: "jq-combo-icon-error-",
                caretIcon: "jq-combo-icon-caret-",
                searchIcon: "jq-combo-icon-search-",
                input: "jq-combo-input-",
                list: "jq-combo-list-",
                iconList: "jq-combo-icons-list-",
                iconWrapper: "jq-combo-icons-wrapper-",
                wrapper1: "first-wrapper-",
                wrapper2: "second-wrapper-",
                wrapper3: "third-wrapper-",
                wrapper4: "forth-wrapper-"
            },
            response: {
                message: "Field is valid.",
                isValid: true,
                isError: false,
                errorCode: null,
                errorMessage: null
            },
            events: {
                iconCreated: function ($div, $input, $iconContainer) { },
                inputCreated: function (plugin, $div, $implementDiv, $input) { },
                listCreated: function (plugin, $div, $implementDiv, $input, data) { },
                sameRequestTwice: function ($div, $input, url, previousText) { },
                beforeSendingRequest: function ($div, $input, url) { },
                responseReceived: function ($div, $input, response) { },
                responseProcessed: function ($div, $input, response) { },
                invalidBefore: function ($div, $input, response) { },
                invalidAfter: function ($div, $input, response) { },
                validBefore: function ($div, $input, response) { },
                validAfter: function ($div, $input, response) { },
                onError: function ($div, $input, jqXHR, textStatus, exceptionMessage, url) { }
            }
        };