//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryDisplay { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
