//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COG
    {
        public COG()
        {
            this.Solds = new HashSet<Sold>();
        }
    
        public long COGID { get; set; }
        public long EmployeeID { get; set; }
        public long ProductID { get; set; }
        public decimal Price { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<Sold> Solds { get; set; }
    }
}
