//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sold
    {
        public long SoldID { get; set; }
        public long ProductID { get; set; }
        public long COGID { get; set; }
        public long ClientID { get; set; }
        public System.DateTime Dated { get; set; }
        public decimal Price { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual COG COG { get; set; }
        public virtual Product Product { get; set; }
    }
}
